import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthChecker from "../lib/AuthChecker";
import Theme from "../lib/theme";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.className} min-h-screen flex flex-col w-full dark:bg-[#202020] bg-gray-50`}
      >
        <Header />
        <main className=" w-full flex flex-col items-center justify-center ">
          <Theme>{children}</Theme>
        </main>
      </body>
    </html>
  );
}
